###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

file_map = {
    
    "clients.baml": "client<llm> GPT4o_mini {\n  provider openai\n  options {\n    model gpt-4o-mini\n    api_key env.OPEN_AI_KEY\n  }\n}",
    "metrics.baml": "// Data Models\nclass Metrics {\n  sentences string[] @description(\"Every sentence should be a function. Basically a function of what is being patented. There must be 8 sentences.\")\n}\nfunction ExtractPatentMetricsFromQuery(patent_text: string) -> Metrics {\n  // LLM client with params you want (not pictured)\n  client GPT4o_mini\n\n  // BAML prompts use Jinja syntax\n  prompt #\"\n    Parse the following patent and return a structured representation of the data in the schema below.\n\n    Your job is to take a search query and extract 8 functions from it.\n\n    Let me give you an example. Let's say the search query is:\n        \n    A coffee maker that dispenses both milk and coffee. The coffee can be made either from beans or from pods. To prevent spilling, there is a metal or plastic grate at the bottom. There is an electric screen to control it and alert the user once it's done.\n\n        The functions you can extract from this are:\n        Brews hot beverage.\n        Dispenses milk.\n        Can use coffee pods.\n        Can use coffee beans.\n        Has refillable water reservoir.\n        Has grate to prevent spillage.\n        Has electric screen for use.\n        Alerts user when done.\n\n    Search Query Text:\n    ---\n    {{ patent_text }}\n    ---\n\n    {{ ctx.output_format }}\n\n    JSON:\n  \"#\n}\n\ntest TestBacterialPrompt {\n  functions [ExtractPatentMetricsFromQuery]\n  args {\n    patent_text #\"\n        A bacteria that divides rapidly and produces beneficial research chemicals.\n    \"#\n  }\n}\n\n\ntest TestCoffeePrompt {\n  functions [ExtractPatentMetricsFromQuery]\n  args {\n    patent_text #\"\n        A machine that dispenses coffee.\n    \"#\n  }\n}\n\ngenerator bamlMetricClient {\n output_type \"python/pydantic\"\n output_dir \"../\"\n version \"0.52.1\"\n}",
}

def get_baml_files():
    return file_map